[package]
name = "chi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
clap = { version = "3.0.10", features = ["derive"] }
pyo3 = { version = "0.15", features = ["auto-initialize"] }
